version: '3.3'

services:

  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: 12345test
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
      - '9211:9211'
    volumes:
      - ./php/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./php/messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf
      - ./symfony:/var/www/project/symfony
      - ./:/var/www/project
    depends_on:
      - database
      - redis

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./symfony:/var/www/project/symfony
      - ./:/var/www/project
      - ./nginx/hosts:/etc/hosts
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/test-test.ru.conf:/etc/nginx/conf.d/test-test.ru.conf
    depends_on:
      - php
      - database

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        - redis_data:/var/lib/redis
    ports:
      - '6397:6397'

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    ports:
      - '5672:5672'

volumes:
  mysql_data:
  redis_data: