framework:
    messenger:
        reset_on_message: true
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
            # sync: 'sync://'
        routing:
            # Route your messages to the transports
            'App\Message\MailNotification': async
            'App\Message\ApiNotification': async
